Repository amaralc/hipeerlab-platform-fe, pull requests merged in 2020-04, with the labels that each got.

#43 Adição de página da equipe
  src/components/Layouts/Team/img/Adriano.png
  src/components/Layouts/Team/img/Artur.png
  src/components/Layouts/Team/img/Azevedo.png
  src/components/Layouts/Team/img/Braulio.png
  src/components/Layouts/Team/img/Bruno.png
  src/components/Layouts/Team/img/Calil.png
  src/components/Layouts/Team/img/Fernando.png
  src/components/Layouts/Team/img/Francisco.png
  src/components/Layouts/Team/img/Frederico.png
  src/components/Layouts/Team/img/Glauco.png
  src/components/Layouts/Team/img/Lazaro.png
  src/components/Layouts/Team/img/Luam.png
  src/components/Layouts/Team/img/Luise.png
  src/components/Layouts/Team/img/Marcos.png
  src/components/Layouts/Team/img/Michel.png
  src/components/Layouts/Team/img/Rafael.png
  src/components/Layouts/Team/img/Sara.png
  src/components/Layouts/Team/img/Thaison.png
  src/components/Layouts/Team/img/Theodor.png
  src/components/Layouts/Team/styles.js
  src/components/NavBar.js
  src/components/TeamContent.js
  src/img/in.png
  src/index.js
  src/pages/Team.js
  src/styles/global.js
Labels: feature

#49 Atualiza página de kits com viseira, elástico e suporte
  src/components/SuppliesContent.js
  src/img/mascara-tiara-acetato.png
Labels: feature

#51 Atualiza dados de face shields e centraliza informação nos cards
  src/components/Card.js
  src/components/SuppliesContent.js
Labels: bug, feature

#52 Adição de página de parceiros e atualização de informações nas demais páginas
  src/components/Card.js
  src/components/Layouts/Partner/styles.js
  src/components/Layouts/Team/img/Larissa.png
  src/components/Layouts/Team/img/Lehmkuhl.png
  src/components/Layouts/Team/img/Max.png
  src/components/NavBar.js
  src/components/PartnerContent.js
  src/components/SuppliesContent.js
  src/components/TeamContent.js
  src/components/VentilatorContent.js
  src/img/comunave.png
  src/img/eme.png
  src/img/larissa.png
  src/img/lmp.png
  src/img/ngd.png
  src/img/project-breathe-4-life-2.png
  src/img/project-breathe-4-life.png
  src/img/project-hipeerlab-croped-2.png
  src/img/project-joinville-croped-2.png
  src/img/project-mit-e-vent-2.png
  src/img/project-mit-e-vent.png
  src/img/project-open-source-ventilator-croped-2.png
  src/img/project-open-source-ventilator-croped.png
  src/img/project-open-ventilator-croped-2.png
  src/img/project-open-ventilator-croped-20200324.png
  src/img/project-oxygen-croped-2.png
  src/img/project-oxygen-croped.png
  src/img/project-ventilaid-2.png
  src/img/project-ventilaid.png
  src/img/pronto.png
  src/index.js
  src/pages/Partner.js
Labels: feature

#55 Move página de parceiros para home
  src/components/HomeContent.js
  src/components/Layouts/Partner/styles.js
  src/components/NavBar.js
  src/components/PartnerContent.js
  src/index.js
  src/pages/Partner.js
Labels: feature

#56 Adiciona partners à página Home
  src/components/HomeContent.js
  src/components/Layouts/Partner/styles.js
  src/components/NavBar.js
  src/components/PartnerContent.js
  src/img/comunave.png
  src/img/lmp.png
  src/index.js
  src/pages/Partner.js
Labels: feature

#57 Atualiza parceiros na pagina Home
  src/components/HomeContent.js
  src/components/Layouts/Partner/styles.js
  src/img/comunave.png
  src/img/lmp.png
Labels: feature

#58 Altera tratativa de protetor para kits
  src/components/AccountabilityContent.js
  src/components/DonateContent.js
  src/components/FaqContent.js
  src/components/HomeContent.js
  src/components/Layouts/Accountability/index.js
  src/components/SuppliesContent.js
  src/components/TeamContent.js
  src/components/VentilatorContent.js
  src/index.js
  src/pages/Accountability.js
  src/pages/Accountability/index.js
  src/pages/Accountability/styles.js
  src/pages/Donate.js
  src/pages/Donate/index.js
  src/pages/Faq.js
  src/pages/Faq/index.js
  src/pages/Home.js
  src/pages/Home/index.js
  src/pages/Partner/styles.js
  src/pages/Supplies.js
  src/pages/Supplies/index.js
  src/pages/Team.js
  src/pages/Team/img/Adriano.png
  src/pages/Team/img/Artur.png
  src/pages/Team/img/Azevedo.png
  src/pages/Team/img/Braulio.png
  src/pages/Team/img/Bruno.png
  src/pages/Team/img/Calil.png
  src/pages/Team/img/Fernando.png
  src/pages/Team/img/Francisco.png
  src/pages/Team/img/Frederico.png
  src/pages/Team/img/Glauco.png
  src/pages/Team/img/Larissa.png
  src/pages/Team/img/Lazaro.png
  src/pages/Team/img/Lehmkuhl.png
  src/pages/Team/img/Luam.png
  src/pages/Team/img/Luise.png
  src/pages/Team/img/Marcos.png
  src/pages/Team/img/Max.png
  src/pages/Team/img/Michel.png
  src/pages/Team/img/Rafael.png
  src/pages/Team/img/Sara.png
  src/pages/Team/img/Thaison.png
  src/pages/Team/img/Theodor.png
  src/pages/Team/index.js
  src/pages/Team/styles.js
  src/pages/Ventilator.js
  src/pages/Ventilator/index.js
  src/styles/global.js
Labels: feature

#60 Adição de projetos de face shield
  src/img/diyFaceShield.png
  src/img/prusaFaceShield.png
  src/pages/Supplies/index.js
Labels: feature

#61 Adiciona botão do instagram na página inicial
  public/index.html
  public/vendor/docs/css/docs.css
  public/vendor/font-awesome/css/font-awesome.css
  public/vendor/font-awesome/fonts/FontAwesome.otf
  public/vendor/font-awesome/fonts/fontawesome-webfont.eot
  public/vendor/font-awesome/fonts/fontawesome-webfont.svg
  public/vendor/font-awesome/fonts/fontawesome-webfont.ttf
  public/vendor/font-awesome/fonts/fontawesome-webfont.woff
  public/vendor/font-awesome/fonts/fontawesome-webfont.woff2
  src/components/NavBar.js
Labels: feature

#62 Corrige cor do footer
  public/vendor/docs/css/docs.css
Labels: feature

#64 Reativa pagina de prestacao de contas
  src/index.js
  src/pages/Accountability/index.js
  src/pages/Accountability/styles.js
  src/pages/Donate/index.js
Labels: feature

#65 FEATURE / CONTENT / Add Cervejaria Ambev Face Shield Project in supplies
  src/img/ambevFaceShield.png
  src/pages/Supplies/index.js
Labels: feature

#66 Reativa prestação de contas, altera target do instagram e adiciona projeto de shield ambev
  src/components/NavBar.js
  src/img/ambevFaceShield.png
  src/index.js
  src/pages/Accountability/index.js
  src/pages/Accountability/styles.js
  src/pages/Donate/index.js
  src/pages/Supplies/index.js
Labels: feature

#67 Adiciona produção de kits na prestacao de contas
  src/pages/Accountability/index.js
Labels: feature

#72 FEATURE / CONTENT / Altera título e descrição no header da pagina de suprimentos
  src/pages/Supplies/index.js
Labels: feature

#73 Atualiza página de contribuição, suprimentos e respiradores
  src/img/ambevFaceShield.png
  src/img/imaginum3dlogo.png
  src/img/project-Ox-Vent-cropped.png
  src/img/project-ambo-vent-cropped.png
  src/img/project-open-vent-bristol-cropped.png
  src/img/project-respira-works-croped.png
  src/img/project-ventilator-pal-croped.png
  src/img/santoshackerlogo.png
  src/img/sicnovaproject.png
  src/pages/Accountability/index.js
  src/pages/Accountability/styles.js
  src/pages/Donate/index.js
  src/pages/Donate/styles.js
  src/pages/Supplies/index.js
  src/pages/Ventilator/index.js
Labels: feature

#76 FIX / ROUTES / Muda rota e pagina "contabilidade" para "transparencia"
  src/index.js
  src/pages/Transparency/index.js
  src/pages/Transparency/styles.js
Labels: enhancement

#78 Altera estilo da pagina de doacao
  src/pages/Donate/index.js
  src/pages/Donate/styles.js
Labels: enhancement

#82 Corrige falha relacionado aos tags iframe
  src/pages/Transparency/index.js
Labels: bug

#83 Fix target blank issues on team page and iframe issues on transparency page
  src/pages/Team/index.js
Labels: bug

#84 Fix target blank issues on team page and iframe issues on transparency page and change project name on package json
  package.json
Labels: bug

#89 Adiciona projetos de faceshield e respiradores e atualiza conteúdo
  src/img/atitude3dproject.png
  src/img/fixitproject.png
  src/img/sos3dproject.png
  src/img/unespproject.png
  src/img/utfprproject.png
  src/pages/Home/index.js
  src/pages/Supplies/index.js
  src/pages/Team/TeamMember.js
  src/pages/Team/index.js
  src/pages/Ventilator/img/project-Ox-Vent-croped.png
  src/pages/Ventilator/img/project-ambo-vent-croped.png
  src/pages/Ventilator/img/project-breathe-4-life-croped.png
  src/pages/Ventilator/img/project-fablab-croped.png
  src/pages/Ventilator/img/project-hipeerlab-v2-croped.png
  src/pages/Ventilator/img/project-mit-e-vent-croped.png
  src/pages/Ventilator/img/project-open-air-croped.png
  src/pages/Ventilator/img/project-open-source-ventilator-croped.png
  src/pages/Ventilator/img/project-open-vent-bristol-croped.png
  src/pages/Ventilator/img/project-open-ventilator-croped.png
  src/pages/Ventilator/img/project-oxygen-croped.png
  src/pages/Ventilator/img/project-respira-works-croped.png
  src/pages/Ventilator/img/project-ventilaid-croped.png
  src/pages/Ventilator/img/project-ventilator-pal-croped.png
  src/pages/Ventilator/img/project-virgin-orbit-croped.png
  src/pages/Ventilator/index.js
Labels: feature

#97 Reseta padrão de cores conforme bootstrap template e atualiza texto de Home
  public/index.html
  public/vendor/bootstrap/css/bootstrap.min.css
  public/vendor/docs/css/docs.css
  src/components/Footer.js
  src/components/Header.js
  src/components/NavBar.js
  src/pages/Donate/index.js
  src/pages/Home/Partner/styles.js
  src/pages/Home/index.js
Labels: enhancement

#98 Adiciona página de notícias
  src/components/NavBar.js
  src/components/NewsCard.js
  src/components/styles.css
  src/index.js
  src/pages/News/img/casos_sc.png
  src/pages/News/img/sample.png
  src/pages/News/img/ufsc_masks.png
  src/pages/News/index.js
Labels: feature

#101 Altera estilo de componentes e reestrutura componentes em pastas
  src/components/Card/styles.js
  src/components/Footer.js
  src/components/Footer/styles.js
  src/components/Header.js
  src/components/Header/styles.js
  src/components/NavBar/index.js
  src/pages/Donate/styles.js
  src/pages/Home/index.js
Labels: enhancement

#105 Aplica regras de estilização no ambiente de desenvolvimento
  .editorconfig
  .eslintrc.js
  .prettierrc
  package-lock.json
  package.json
  src/App.js
  src/components/Card/index.js
  src/components/Card/styles.js
  src/components/Carousel/index.js
  src/components/Footer/index.js
  src/components/Footer/styles.js
  src/components/Header/index.js
  src/components/Header/styles.js
  src/components/NavBar/index.js
  src/index.js
  src/pages/Donate/index.js
  src/pages/Donate/styles.js
  src/pages/Faq/index.js
  src/pages/Home/Partner/index.js
  src/pages/Home/Partner/styles.js
  src/pages/Home/index.js
  src/pages/Home/styles.js
  src/pages/News/NewsCard/index.js
  src/pages/News/index.js
  src/pages/Supplies/index.js
  src/pages/Team/TeamMember/index.js
  src/pages/Team/TeamMember/styles.js
  src/pages/Team/index.js
  src/pages/Team/styles.js
  src/pages/Transparency/index.js
  src/pages/Transparency/styles.js
  src/pages/Ventilator/index.js
  src/serviceWorker.js
  src/styles/global.js
  yarn.lock
Labels: feature

#106 Configura rotas e reestrutura arquivos da aplicação
  package.json
  src/App.js
  src/pages/Dashboard/index.js
  src/pages/Dashboard/styles.js
  src/pages/Profile/index.js
  src/pages/Profile/styles.js
  src/pages/SignIn/index.js
  src/pages/SignIn/styles.js
  src/pages/SignUp/index.js
  src/pages/SignUp/styles.js
  src/routes/index.js
  src/services/history.js
  yarn.lock
Labels: feature

#107 Configura Reactotron
  docs/fe.md
  package.json
  src/App.js
  src/config/ReactotronConfig.js
  template.js
  yarn.lock
Labels: feature

#108 Cria <Route /> com regras de redirecionamento e configura rotas privadas
  .eslintrc.js
  docs/fe.md
  package.json
  src/pages/Dashboard/index.js
  src/pages/Profile/index.js
  src/pages/SignIn/index.js
  src/pages/SignUp/index.js
  src/routes/Route.js
  src/routes/index.js
Labels: feature

#109 Cria layouts e condições de renderização de layout dependendo da rota e status do usuário na aplicação
  docs/fe.md
  src/pages/_layouts/auth/index.js
  src/pages/_layouts/auth/styles.js
  src/pages/_layouts/default/index.js
  src/pages/_layouts/default/styles.js
  src/routes/Route.js
Labels: feature

#110 Adiciona regras para renderização do componente header
  src/App.js
  src/components/Header/index.js
  src/components/Header/styles.js
  src/pages/Dashboard/index.js
  src/pages/Profile/index.js
  src/pages/SignIn/index.js
  src/pages/SignUp/index.js
  src/pages/_layouts/auth/styles.js
  src/pages/_layouts/default/styles.js
  src/routes/index.js
  src/styles/global.js
Labels: bug, feature

#111 Utilizando root import
  .eslintrc.js
  config-overrides.js
  docs/fe.md
  jsconfig.json
  package.json
  src/pages/_layouts/auth/styles.js
  src/pages/_layouts/default/styles.js
  src/routes/Route.js
  yarn.lock
Labels: feature

#113 Configura autenticação do usuário
  package.json
  src/pages/SignIn/index.js
  src/routes/Route.js
  src/services/api.js
  src/store/modules/auth/actions.js
  src/store/modules/auth/reducer.js
  src/store/modules/auth/sagas.js
  yarn.lock
Labels: feature

#115 Exibindo toasts
  docs/fe.md
  package.json
  src/App.js
  src/store/modules/auth/sagas.js
  src/styles/global.js
  yarn.lock
Labels: feature

#112 Update news page style
  src/pages/News/NewsCard/index.js
  src/pages/News/NewsCard/styles.js
Labels: feature, style

#118 Adição de página de notícias, atualização da pagina de contribuição e configuração de eslint
  .editorconfig
  .eslintrc.js
  .prettierrc
  package-lock.json
  package.json
  src/App.js
  src/components/Card/index.js
  src/components/Card/styles.js
  src/components/Carousel/index.js
  src/components/Footer/index.js
  src/components/Footer/styles.js
  src/components/Header/index.js
  src/components/Header/styles.js
  src/components/NavBar/index.js
  src/index.js
  src/pages/Donate/Bank/index.js
  src/pages/Donate/Bank/styles.js
  src/pages/Donate/img/logo-vakinha.png
  src/pages/Donate/index.js
  src/pages/Donate/styles.js
  src/pages/Faq/index.js
  src/pages/Home/Partner/index.js
  src/pages/Home/Partner/styles.js
  src/pages/Home/index.js
  src/pages/Home/styles.js
  src/pages/News/NewsCard/index.js
  src/pages/News/NewsCard/styles.js
  src/pages/News/index.js
  src/pages/Supplies/index.js
  src/pages/Team/TeamMember/index.js
  src/pages/Team/TeamMember/styles.js
  src/pages/Team/index.js
  src/pages/Team/styles.js
  src/pages/Transparency/index.js
  src/pages/Transparency/styles.js
  src/pages/Ventilator/img/project-aau-pandemic-ventilator-croped.png
  src/pages/Ventilator/img/project-open-breath-croped.png
  src/pages/Ventilator/img/project-prevail-ny-croped.png
  src/pages/Ventilator/img/project-vent-core-croped.png
  src/pages/Ventilator/index.js
  src/serviceWorker.js
  src/styles/global.js
  yarn.lock
Labels: bug, feature

#119 Alteração de dados bancários da conta NuBank
  src/pages/Donate/Bank/index.js
Labels: bug

#121 FIX / Corrige dados e adiciona conta bradesco
  src/pages/Donate/Bank/index.js
Labels: bug

#122 FIX / CONTENT / Corrige numero da conta do bradesco
  src/pages/Donate/Bank/index.js
Labels: bug

#123 Correção do número da conta do Bradesco
  src/pages/Donate/Bank/index.js
Labels: bug
